### ISSUE TITLE
Feature Request - suport network ID as input to manage existing networks

### ISSUE THREAD

**Issue by craSH** [zerotier/terraform-zerotier-network#1]
It'd be great if an existing network ID could be provided as input to allow transitioning from manually created/managed networks to using Terraform to manage them, without needing to create new networks in doing so (and moving clients to them)

**Comment by someara** [comment]
Hi Ian!

We're *definitely* planning on adding this.

The proper thing to do is implement resource importing on the provider.
https://www.terraform.io/docs/cli/import/index.html

The issue is being tracked here:
https://github.com/zerotier/terraform-provider-zerotier/issues/17
I'm gonna close the issue on this repo, to avoid duplication.

Thanks for reporting!

-s

**Comment by someara** [comment]
Hello!
Support for importing networks was released in provider version 1.2.0 
https://github.com/zerotier/terraform-provider-zerotier/commit/db08f1dbf2f1d331c54884856e9fab6b18b8e797
